# config
http:
  port: 8000
  port-metrics: 9898
  http-server-timeout: 30s
  http-server-shutdown-timeout: 5s

redis:
  MaxIdle: 1000
  IdleTimeout: 30s
  ConnectTimeout: 30s
  ReadTimeout: 5s
  WriteTimeout: 5s
  Host: 127.0.0.1
  Port: 6379
  Password: "123456"
  DB: 0

logger:
  level: debug
  output-paths:
    - "stderr"
    - "logs/go-dev.log"
  error-output-paths:
    - "stderr"
    - "logs/go-dev.error.log"

database:
  user: root
  password: "123456"
  host: 127.0.0.1
  port: 3306
  dbname: test
  timeout: 30s
  read-timeout: 5s
  write-timeout: 5s